name: Build BusyBox-w32

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:trixie # ucrt64 要求 debian 13 +

    steps:
      - name: Install build dependencies
        run: apt-get update && apt-get install -y make gcc gcc-mingw-w64-x86-64 gcc-mingw-w64-ucrt64 git bzip2

      - name: Clone
        run: |
          git clone --depth 1 -b ${{ github.event.inputs.branch }} https://github.com/rmyorston/busybox-w32.git
          cd busybox-w32
          git log -1 --format="%h (%s)" > build-info.txt

      - name: Build Mingw64
        run: |
          cd busybox-w32
          make mingw64_defconfig
          make -j$(nproc)
          mv busybox.exe busybox-mingw64.exe

      - name: Build Mingw64 Unicode
        run: |
          cd busybox-w32
          make mingw64u_defconfig
          make -j$(nproc)
          mv busybox.exe busybox-mingw64u.exe

      - name: Build UCRT64
        run: |
          cd busybox-w32
          sed 's/CROSS_COMPILER_PREFIX="x86_64-w64-mingw32-"/CROSS_COMPILER_PREFIX="x86_64-w64-mingw32ucrt-"/' configs/mingw64_defconfig > configs/ucrt64_defconfig
          make ucrt64_defconfig
          make -j$(nproc)
          mv busybox.exe busybox-ucrt64.exe

      - name: Build UCRT64 Unicode
        run: |
          cd busybox-w32
          sed 's/CROSS_COMPILER_PREFIX="x86_64-w64-mingw32-"/CROSS_COMPILER_PREFIX="x86_64-w64-mingw32ucrt-"/' configs/mingw64u_defconfig > configs/ucrt64u_defconfig
          make ucrt64u_defconfig
          make -j$(nproc)
          mv busybox.exe busybox-ucrt64u.exe

      - name: Output
        run: |
          mkdir -p release
          cp busybox-w32/busybox-mingw64.exe release/
          cp busybox-w32/busybox-mingw64u.exe release/
          cp busybox-w32/busybox-ucrt64.exe release/
          cp busybox-w32/busybox-ucrt64u.exe release/
          [ -f busybox-w32/LICENSE ] && cp busybox-w32/LICENSE release/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Auto Build BusyBox-w32
            Tag: ${{ github.event.inputs.branch }}
            Build Time: ${{ github.event.head_commit.timestamp }}
          files: |
            release/*
            release/LICENSE
          draft: false
          prerelease: false
