name: Trigger

on:
  schedule:
    - cron: "0 3 * * *" # 每天凌晨3点触发
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Version Check
        run: |
          git clone --quiet --no-checkout https://github.com/rmyorston/busybox-w32.git
          latest_version=$(cd busybox-w32 && git tag --sort=-creatordate | head -n 1)

          last_version=$(git tag --sort=-creatordate | head -n 1)

          if [ "$latest_version" != "$last_version" ]; then
            echo "Version changed from $last_version to $latest_version"
            echo "VERSION_CHANGED=true" >> $GITHUB_ENV
            echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV
          else
            echo "Version unchanged at $latest_version"
          fi

      - name: Create Tag
        if: env.VERSION_CHANGED == 'true'
        run: |
          # 创建标签
          git tag ${{ env.LATEST_VERSION }}
          # 推送标签到远程仓库
          git push origin ${{ env.LATEST_VERSION }}
          # 保存最新版本到缓存
          echo ${{ env.LATEST_VERSION }} > .cache/version
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }} # 使用自定义token
